location: .gitman
sources:
- name: example_ros_pluginlib
  type: git
  repo: https://github.com/ctu-mrs/example_ros_pluginlib.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/example_ros_pluginlib
  scripts:
  -
- name: example_ros_uav
  type: git
  repo: https://github.com/ctu-mrs/example_ros_uav.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/example_ros_uav
  scripts:
  - git submodule update --init --recursive
- name: example_ros_vision
  type: git
  repo: https://github.com/ctu-mrs/example_ros_vision.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/example_ros_vision
  scripts:
  - git submodule update --init --recursive
sources_locked:
- name: example_ros_pluginlib
  type: git
  repo: https://github.com/ctu-mrs/example_ros_pluginlib.git
  sparse_paths:
  -
  rev: 1171c60531a92f42c0cf9b56bb20654a687b3993
  link: ros_packages/example_ros_pluginlib
  scripts:
  -
- name: example_ros_uav
  type: git
  repo: https://github.com/ctu-mrs/example_ros_uav.git
  sparse_paths:
  -
  rev: b6f3cd4a3de16dd77b87dd3f2a186170407e5b33
  link: ros_packages/example_ros_uav
  scripts:
  - git submodule update --init --recursive
- name: example_ros_vision
  type: git
  repo: https://github.com/ctu-mrs/example_ros_vision.git
  sparse_paths:
  -
  rev: e2e7578a63084e44b9f6502a93726df58b25506e
  link: ros_packages/example_ros_vision
  scripts:
  - git submodule update --init --recursive
