location: .gitman
sources:
- name: example_ros_pluginlib
  type: git
  repo: https://github.com/ctu-mrs/example_ros_pluginlib.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/example_ros_pluginlib
  scripts:
  - git submodule update --init --recursive
- name: example_ros_uav
  type: git
  repo: https://github.com/ctu-mrs/example_ros_uav.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/example_ros_uav
  scripts:
  - git submodule update --init --recursive
- name: example_ros_vision
  type: git
  repo: https://github.com/ctu-mrs/example_ros_vision.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/example_ros_vision
  scripts:
  - git submodule update --init --recursive
sources_locked:
- name: example_ros_pluginlib
  type: git
  repo: https://github.com/ctu-mrs/example_ros_pluginlib.git
  sparse_paths:
  -
  rev: d15cbcce722399db55451a6e84326a7175c9d3c5
  link: ros_packages/example_ros_pluginlib
  scripts:
  - git submodule update --init --recursive
- name: example_ros_uav
  type: git
  repo: https://github.com/ctu-mrs/example_ros_uav.git
  sparse_paths:
  -
  rev: 4805f60ab939953d90548438e2a698023db0bd8a
  link: ros_packages/example_ros_uav
  scripts:
  - git submodule update --init --recursive
- name: example_ros_vision
  type: git
  repo: https://github.com/ctu-mrs/example_ros_vision.git
  sparse_paths:
  -
  rev: 3c08b98c9b7af0c59f3e9d0ea54febd733896d6e
  link: ros_packages/example_ros_vision
  scripts:
  - git submodule update --init --recursive
