simulation_rate: 200
clock_rate: 200
realtime_factor: 0.5

uav_names: [
  "uav1",
]

individual_takeoff_platform:
  enabled: false

uav1:
  type: "x500"
  spawn:
    x: 0.0
    y: 0.0
    z: 2.0
    heading: 0
