simulation_rate: 250
clock_rate: 250
realtime_factor: 1.0

uav_names: [
  "uav1",
]

individual_takeoff_platform:
  enabled: false

uav1:
  type: "x500"
  spawn:
    x: 10.0
    y: 15.0
    z: 2.0
    heading: 0
